name: CI

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js 24.x
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: "npm"

      - name: Install Zig 0.16.x
        shell: bash
        run: |
          curl -fsSL https://www.zvm.app/install.sh | bash

          export ZVM_INSTALL="$HOME/.zvm/self"
          export PATH="$ZVM_INSTALL:$PATH"

          zvm install 0.16
          zvm use 0.16

          echo "$HOME/.zvm/bin" >> "$GITHUB_PATH"
          echo "$ZVM_INSTALL" >> "$GITHUB_PATH"

          zig version

      - run: npm ci

      - run: zig fmt --check .
      - run: zig build -Dtarget=x86_64-linux-musl --release=small

      - run: npm run build --if-present
      - run: npm run test:ci


