name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CI: true

    steps:
      - uses: actions/checkout@v7

      - name: Setup Node.js 24.x
        uses: actions/setup-node@v7
        with:
          node-version: 24.x
          cache: "npm"

      - name: Setup Zig 0.16.0
        uses: vercel-labs/setup-zig@v1
        with:
          version: 0.16.0

      - run: npm ci

      - name: Check Zig Formatting
        run: zig fmt --check src/ tests/ build.zig

      - name: Run Zig Tests
        run: zig build test --summary all

      - name: Build Native Release Addon
        run: zig build --release=small

      - name: Build CLI & Run Lint / Tests
        run: |
          cp -f zig-out/neostaged-unknown.node packages/cli/bin/neostaged.node
          npm run --prefix packages/cli build
          npm run --prefix packages/cli lint
          npm run --prefix packages/cli test
